# Esta línea activa el modo estricto de Very Good Analysis
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- TUS REGLAS PERSONALIZADAS ---
    
    # Excepción: Si no quieres documentar cada variable (///), descomenta la siguiente línea:
    public_member_api_docs: false

    # Rendimiento
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true

    # Limpieza
    avoid_print: true 
    prefer_single_quotes: true
    prefer_final_locals: true
    sized_box_for_whitespace: true
    prefer_relative_imports: true