name: salufit_app
description: Aplicación de gestión para Centro Salufit.
publish_to: 'none'
version: 2.0.7+137

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  chewie: ^1.8.5
  cloud_firestore: ^5.0.0
  cloud_functions: ^5.0.0
  crypto: ^3.0.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.0.0
  excel: ^4.0.6
  file_picker: ^8.1.0
  firebase_analytics: ^11.6.0
  firebase_app_check: ^0.3.1
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: "^3.0.0-dev.0"
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  image_picker: ^1.1.2
  intl: ^0.20.0
  json_annotation: ^4.9.0
  local_auth: ^2.2.0
  mobile_scanner: ^7.1.4
  network_info_plus: ^5.0.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  pdf: ^3.10.0
  permission_handler: ^11.3.0
  printing: ^5.13.0
  qr_flutter: ^4.1.0
  riverpod_annotation: "^3.0.0-dev.0"
  shared_preferences: ^2.2.0
  skeletonizer: ^2.1.2
  url_launcher: ^6.3.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: "^3.0.0-dev.0"
  very_good_analysis: ^5.1.0
  integration_test:
    sdk: flutter
  # Testing UI y mocks
  fake_cloud_firestore: ^3.0.0
  firebase_auth_mocks: ^0.14.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo_salufit.png
    - assets/login_bg.jpg
    - assets/login_logo.png
    - assets/watermark_bg.jpg
    - assets/app_icon.png
    
