// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNJeg6SLVg6WYGwg2RTmoOtaTl3wnp6ts',
    appId: '1:682610782118:web:02fa1736ac64b1c900e967',
    messagingSenderId: '682610782118',
    projectId: 'salufitnewapp',
    authDomain: 'salufitnewapp.firebaseapp.com',
    storageBucket: 'salufitnewapp.firebasestorage.app',
    measurementId: 'G-36VE2KBVLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZqrHi4neZxNpoZ6Kg-rYtvE8nnP93jIU',
    appId: '1:682610782118:android:504b41e7d133453e00e967',
    messagingSenderId: '682610782118',
    projectId: 'salufitnewapp',
    storageBucket: 'salufitnewapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw4IHGoLh4o5QWb5VAzeSSrWeGC6aQ--Y',
    appId: '1:682610782118:ios:804e25fab43b572500e967',
    messagingSenderId: '682610782118',
    projectId: 'salufitnewapp',
    storageBucket: 'salufitnewapp.firebasestorage.app',
    iosBundleId: 'com.example.salufitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw4IHGoLh4o5QWb5VAzeSSrWeGC6aQ--Y',
    appId: '1:682610782118:ios:804e25fab43b572500e967',
    messagingSenderId: '682610782118',
    projectId: 'salufitnewapp',
    storageBucket: 'salufitnewapp.firebasestorage.app',
    iosBundleId: 'com.example.salufitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNJeg6SLVg6WYGwg2RTmoOtaTl3wnp6ts',
    appId: '1:682610782118:web:c29bc2d898e06dc200e967',
    messagingSenderId: '682610782118',
    projectId: 'salufitnewapp',
    authDomain: 'salufitnewapp.firebaseapp.com',
    storageBucket: 'salufitnewapp.firebasestorage.app',
    measurementId: 'G-HXPW7BM2ZQ',
  );
}
